name: Deploy to azure

on:
 push:
   branches: [main, test]
 workflow_dispatch:
  inputs:
    environment:
      description: 'environment to deploy'
      required: true
      default: 'dev'
      type: choice
      options:
      - dev
      - qa
      - uat
    tags:
      description: 'Test scenario tags'
      required: false
      type: boolean
      
env:
  NODE_JS: '20.x'
  TENANTID: ${{ secret.AZURE_TENANT_ID }}
  SUBSCRIPTIONID: ${{ AZURE_SUBSCRIPTION_ID }}
  CLIENTID: ${{ secrets.AZURE_CLIENT_ID }}
  CLIENT-SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    
